# Generated by Django 3.2 on 2021-11-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TakeOutSystem', '0002_order_dish_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('0', '预定状态'), ('1', '订单开始'), ('2', '完成支付'), ('3', '商家已接单'), ('4', '完成备餐'), ('5', '骑手已接单'), ('6', '完成送达')], default='预定状态', max_length=20),
        ),
    ]
