# Generated by Django 3.2 on 2021-11-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TakeOutSystem', '0004_menu_special_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='special_offer',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
