# Generated by Django 3.2 on 2021-11-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TakeOutSystem', '0005_auto_20211126_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='special_offer',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
